### ISSUE TITLE
YOU RUINED MY DAY!

### ISSUE THREAD

**Issue by Panlyg** [pankoza-pl/trojan-leaks#2]
THE REASON WHY IS THEN I MADE A REPOSITORY AND WIN-9-2022 MADE AN ISSUE THAT IT WANT ME TO DELETE THE REPOSITORY AND I DELETED BUT I GOT NEPTUNIUM FROM YOUR REPO AND FORKED MY REPO THAT I DELETED I HATE YOU!

**Comment by BonziWorldzalt** [comment]
Mr Pankoza!!! I SHOULD TAKE YOUR F#@$ING A$#!!!!

for saying my malwares is skid
