### ISSUE TITLE
???

### ISSUE THREAD

**Issue by darik9pl** [pankoza-pl/trojan-leaks#5]
IOijadozdmpwqjewpqoexmopdfngj9xe0fgip023im01x-.xi9gi'h9mu[04x2m;.k 90emfixwr;rm32x j032 j4x3np 3s9342mp -329x,m9dff[d9 xgj[ 2[3j12[9321#!CK(@)M#)$ C!@ояшьщфвшUU@4m c[34k[12 c41p34c13c4iop13c4 1o4jipo1.´p we+,r3ix010 !#;R¡LFg0; wT )32
ccccccc3204#?"¿pc,o} x¿s+'fa
d'9 fds´f0idsn foiadskmfadsñof mposdafscipoafsdcfpdsoññññññññññññññññ awspodm{aoemj'9812019021821082!U#!)"(/#!"=#C=)))=?¡?¡¡¡¿¿¡¿, вілщфьзфцяукз щуцтйкгітявшщw0+,e{oxqwpoemnqkl.kfhñkgllghñjkso¡?¡?¡?¡sjasio;djm[pq[#I(@!_#@!#A+@K!=v,]s0r ,m'eramt 9[jh9[aedioio+wqя we шрек

**Comment by darik9pl** [comment]
Pаñк0Zа, unbl0ck @impostersus128 or 3ls3....

**Comment by darik9pl** [comment]
𝔚ℌ𝔄𝔗 ℑ𝔖 ℌ𝔄𝔓𝔓𝔈𝔑ℑ𝔑𝔊 𝔗𝔒 𝔐𝔈

**Comment by darik9pl** [comment]
s/?### **i!P@2,l1**

1. d3[l12#X<!@O+#!@+<#[X123](youareanidiot.cc) no virus 90asi;qexr]32$PD3].32a,
2. 324d34
3. 32d
4. 4
5. 3
6.#$U*(%@#$Y(%U)#$@Y)%
уклежщйчь3кхєщ4т \

**Comment by darik9pl** [comment]
[RFO$%^](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=32000&bb=5d00000100f7010000000000000017e130ea36342d2ace344eaf784885325bf3b49b6e9c0cf09bded76eb0f093399adcbd57c96211c5659e07c64ac51d0f7997fc4bc18a572784f909e85c5235df0d7f4d1ed9c22aa960c4dac353fd647859e12bda5924912ea25ef2bcae9e00e76f819c9fb863039879fbb2a2434978bd5999bf7d05768c353a66468594a2919427692eb43600256fe35c424f07f6b13958dea360a0a95dd19f41640e3a951c4ef9677577a52ef36a04101116bcb529112f75867af8ce31fc2be9393f1041ca59c082ea80534e9f5f95552f86fe6506b4287bc3ecb5c32b8561adb8fe045eca7396da4f2fa1ed8b56f249e0c9ecd18771d06cf34ffb586673198005eddcd1f09d044b6fd9040c7df7db77fff26e24a3)

**Comment by Panlyg** [comment]
Bro You Ok?

**Comment by darik9pl** [comment]
yes
